services:
  af:
    container_name: airflow_container
    image: apache/airflow:3.0.0
    ports:
      - 8000:8080

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/credentials/gcp_key.json
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./credentials:/opt/airflow/credentials
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -c "
      pip install -r /opt/airflow/requirements.txt &&
      airflow db migrate &&
      airflow standalone
      "

